install.packages('KoNLP')
library(KoNLP)
install.packages('stringi')
library(stringi)
install.packages('rlang')
library(rlang)
useSystemDic()
useSejongDic()
useNIADic()
extractNoun('나는 학생이다.')